New "speexdec" resampler
roc-streaming/roc-toolkit pull request #595
Opened 2023-10-05 17:50 UTC by gavv

PR contains 3 commits:

* relax requirements in resampler tests: use more smooth input, and 99% percentile for input & output comparisons
* implement DecimationResampler (decorator for IResampler that add decimation for dynamic part of scaling factor, a.k.a. multiplier), and register "speexdec" backend that combines DecimationResampler + SpeexResampler
* improve resampler tests: cleanup, cover multiple rates and profiles, add "scaling_trend" test

2023-10-08 18:03 UTC, baranovmv requested changes

2023-10-09 10:47 UTC, gavv commented on src/internal_modules/roc_audio/decimation_resampler.cpp
> +            std::min(in_size_ - in_pos_, (size_t)ceilf(out_acc_ / num_ch_) * num_ch_));
Agree, this is an artifact from an older version. Fixed.

2023-10-09 12:29 UTC, gavv commented
Update: added `ROC_RESAMPLER_BACKEND_SPEEXDEC` to C API

2023-10-09 19:51 UTC, baranovmv approved these changes

2023-10-09 19:51 UTC, merged