Issue 766: Refactored Boolean Returns to StatusCode in IComposer
roc-streaming/roc-toolkit pull request #789
Opened 2024-12-22 15:24 UTC by sayedMurtadha

2024-12-23 06:45 UTC, sayedMurtadha commented
@gavv Can you please review the PR? Thanks

2025-01-16 10:18 UTC, gavv requested changes
Thanks a lot for the patch! Changes look fine, just a few minor comments.

2025-01-16 10:18 UTC, gavv commented on src/tests/roc_audio/test_depacketizer.cpp
> +          == status::StatusOK);
Here and in other tests: instead of:

```
CHECK(foo() == status::StatusOK);
```

please use:

```
LONGS_EQUAL(status::StatusOK, foo());
```

This way, on failure cpputest will print value returned by `foo()`, which makes debugging easier.

2025-01-16 10:18 UTC, gavv commented on src/internal_modules/roc_packet/icomposer.h
>      align(core::Slice<uint8_t>& buffer, size_t header_size, size_t payload_alignment) = 0;
Please add `ROC_ATTR_NODISCARD` to all methods that return StatusCode. It
instructs compiler to issue a warning if the caller forgets to check function
return value.

Also please add this attribute to all derived classes (rtp::Composer, fec::Composer, etc), because attributes are not inherited.

2025-01-16 10:18 UTC, gavv commented on src/internal_modules/roc_packet/shipper.cpp
>          }
We need to forward status from composer here.

2025-01-16 10:18 UTC, gavv commented on src/internal_modules/roc_fec/block_writer.cpp
>      }
nitpick: Please add `roc_log` call similar to how we do it in `make_repair_packet_()`.

2025-01-16 10:18 UTC, gavv commented on src/internal_modules/roc_audio/packetizer.cpp
>      }
Since we're now able to handle errors properly, could you please replace
`roc_panic` with `roc_log` here and return status from `pad_packet_()` and
forward it from `end_packet_()`?

2025-01-16 10:18 UTC, gavv commented on src/internal_modules/roc_fec/block_writer.cpp
>          }
nit: Please add `roc_log` call similar to how we do it in `make_repair_packet_()`.

2025-01-16 10:18 UTC, gavv commented on src/internal_modules/roc_rtcp/composer.cpp
>      }
A more correct status here would be `StatusBadArg`.

However, seems that all other composers treat invalid arguments as a violation and panic instead. Could you please replace `roc_log` + `StatusBadOperation` here with a panic as well?

2025-01-19 09:50 UTC, sayedMurtadha commented on src/internal_modules/roc_rtcp/composer.cpp
>      }
Done

2025-01-19 09:50 UTC, sayedMurtadha commented on src/internal_modules/roc_fec/block_writer.cpp
>          }
Done

2025-01-19 09:50 UTC, sayedMurtadha commented on src/internal_modules/roc_audio/packetizer.cpp
>      }
Done

2025-01-19 09:51 UTC, sayedMurtadha commented on src/internal_modules/roc_fec/block_writer.cpp
>      }
Done

2025-01-19 09:51 UTC, sayedMurtadha commented on src/internal_modules/roc_packet/shipper.cpp
>          }
Done

2025-01-19 09:51 UTC, sayedMurtadha commented on src/internal_modules/roc_packet/icomposer.h
>      align(core::Slice<uint8_t>& buffer, size_t header_size, size_t payload_alignment) = 0;
Done

2025-01-19 09:52 UTC, sayedMurtadha commented on src/tests/roc_audio/test_depacketizer.cpp
> +          == status::StatusOK);
Done

2025-01-21 07:10 UTC, gavv approved these changes

2025-01-21 08:09 UTC, merged

2025-01-21 08:11 UTC, gavv commented
Thanks!